#!/usr/bin/env python

import os
import shutil
import sys
import torch

from diffusers import StableDiffusionPipeline
from consistencydecoder import ConsistencyDecoder


# append project directory to path so predict.py can be imported
sys.path.append(".")

from predict import MODEL_CACHE, MODEL_ID

ConsistencyDecoder(device="cuda:0", download_root="/src/consistencydecoder-cache")

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionPipeline.from_pretrained(
    MODEL_ID, torch_dtype=torch.float16, device="cuda:0"
)

pipe.save_pretrained(MODEL_CACHE)
